version: '3'

services:

    web:
      build: ./etc
      volumes:
        - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
      ports:
        - 80:80
        - 443:443
      working_dir: ${APP_PATH_CONTAINER}
      command: composer update
      depends_on:
        - db

    db:
      image: mysql:5.7
      ports:
        - 3306:3306
      restart:
        always
      environment:
        MYSQL_ROOT_PASSWORD: oyctyBbGs5wVB9
      volumes:
        - ${DB_PATH_HOST}:/var/lib/mysql

    adminer:
      image: adminer
      restart:
        always
      ports:
        - 6080:8080
      depends_on:
        - db